//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("WZNTModel", "fk_WZNTArtikelVarianten_WZNTArtikel", "WZNTArtikel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.WZNTArtikel), "WZNTArtikelVarianten", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.WZNTArtikelVarianten), true)]
[assembly: EdmRelationshipAttribute("WZNTModel", "fk_WZNTArtikelVarianten_WZNTArtVarAuspr", "WZNTArtVarAuspr", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data.WZNTArtVarAuspr), "WZNTArtikelVarianten", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data.WZNTArtikelVarianten), true)]

#endregion

namespace Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WZNTEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WZNTEntities object using the connection string found in the 'WZNTEntities' section of the application configuration file.
        /// </summary>
        public WZNTEntities() : base("name=WZNTEntities", "WZNTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WZNTEntities object.
        /// </summary>
        public WZNTEntities(string connectionString) : base(connectionString, "WZNTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WZNTEntities object.
        /// </summary>
        public WZNTEntities(EntityConnection connection) : base(connection, "WZNTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GruSysAPiJobl> GruSysAPiJobl
        {
            get
            {
                if ((_GruSysAPiJobl == null))
                {
                    _GruSysAPiJobl = base.CreateObjectSet<GruSysAPiJobl>("GruSysAPiJobl");
                }
                return _GruSysAPiJobl;
            }
        }
        private ObjectSet<GruSysAPiJobl> _GruSysAPiJobl;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GruSysAPiJobSt> GruSysAPiJobSt
        {
            get
            {
                if ((_GruSysAPiJobSt == null))
                {
                    _GruSysAPiJobSt = base.CreateObjectSet<GruSysAPiJobSt>("GruSysAPiJobSt");
                }
                return _GruSysAPiJobSt;
            }
        }
        private ObjectSet<GruSysAPiJobSt> _GruSysAPiJobSt;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GruSysStandort> GruSysStandort
        {
            get
            {
                if ((_GruSysStandort == null))
                {
                    _GruSysStandort = base.CreateObjectSet<GruSysStandort>("GruSysStandort");
                }
                return _GruSysStandort;
            }
        }
        private ObjectSet<GruSysStandort> _GruSysStandort;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WZNTArtikel> WZNTArtikel
        {
            get
            {
                if ((_WZNTArtikel == null))
                {
                    _WZNTArtikel = base.CreateObjectSet<WZNTArtikel>("WZNTArtikel");
                }
                return _WZNTArtikel;
            }
        }
        private ObjectSet<WZNTArtikel> _WZNTArtikel;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WZNTArtikelVarianten> WZNTArtikelVarianten
        {
            get
            {
                if ((_WZNTArtikelVarianten == null))
                {
                    _WZNTArtikelVarianten = base.CreateObjectSet<WZNTArtikelVarianten>("WZNTArtikelVarianten");
                }
                return _WZNTArtikelVarianten;
            }
        }
        private ObjectSet<WZNTArtikelVarianten> _WZNTArtikelVarianten;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WZNTArtVarAuspr> WZNTArtVarAuspr
        {
            get
            {
                if ((_WZNTArtVarAuspr == null))
                {
                    _WZNTArtVarAuspr = base.CreateObjectSet<WZNTArtVarAuspr>("WZNTArtVarAuspr");
                }
                return _WZNTArtVarAuspr;
            }
        }
        private ObjectSet<WZNTArtVarAuspr> _WZNTArtVarAuspr;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GruSysAPiJobl EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGruSysAPiJobl(GruSysAPiJobl gruSysAPiJobl)
        {
            base.AddObject("GruSysAPiJobl", gruSysAPiJobl);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GruSysAPiJobSt EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGruSysAPiJobSt(GruSysAPiJobSt gruSysAPiJobSt)
        {
            base.AddObject("GruSysAPiJobSt", gruSysAPiJobSt);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GruSysStandort EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGruSysStandort(GruSysStandort gruSysStandort)
        {
            base.AddObject("GruSysStandort", gruSysStandort);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WZNTArtikel EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWZNTArtikel(WZNTArtikel wZNTArtikel)
        {
            base.AddObject("WZNTArtikel", wZNTArtikel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WZNTArtikelVarianten EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWZNTArtikelVarianten(WZNTArtikelVarianten wZNTArtikelVarianten)
        {
            base.AddObject("WZNTArtikelVarianten", wZNTArtikelVarianten);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WZNTArtVarAuspr EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWZNTArtVarAuspr(WZNTArtVarAuspr wZNTArtVarAuspr)
        {
            base.AddObject("WZNTArtVarAuspr", wZNTArtVarAuspr);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WZNTModel", Name="GruSysAPiJobl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GruSysAPiJobl : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GruSysAPiJobl object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="jOB_ID">Initial value of the JOB_ID property.</param>
        public static GruSysAPiJobl CreateGruSysAPiJobl(global::System.Int32 id, global::System.Int32 jOB_ID)
        {
            GruSysAPiJobl gruSysAPiJobl = new GruSysAPiJobl();
            gruSysAPiJobl.ID = id;
            gruSysAPiJobl.JOB_ID = jOB_ID;
            return gruSysAPiJobl;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JOB_ID
        {
            get
            {
                return _JOB_ID;
            }
            set
            {
                OnJOB_IDChanging(value);
                ReportPropertyChanging("JOB_ID");
                _JOB_ID = StructuralObject.SetValidValue(value, "JOB_ID");
                ReportPropertyChanged("JOB_ID");
                OnJOB_IDChanged();
            }
        }
        private global::System.Int32 _JOB_ID;
        partial void OnJOB_IDChanging(global::System.Int32 value);
        partial void OnJOB_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JOB_Bez
        {
            get
            {
                return _JOB_Bez;
            }
            set
            {
                OnJOB_BezChanging(value);
                ReportPropertyChanging("JOB_Bez");
                _JOB_Bez = StructuralObject.SetValidValue(value, true, "JOB_Bez");
                ReportPropertyChanged("JOB_Bez");
                OnJOB_BezChanged();
            }
        }
        private global::System.String _JOB_Bez;
        partial void OnJOB_BezChanging(global::System.String value);
        partial void OnJOB_BezChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Parameterdatei
        {
            get
            {
                return _Parameterdatei;
            }
            set
            {
                OnParameterdateiChanging(value);
                ReportPropertyChanging("Parameterdatei");
                _Parameterdatei = StructuralObject.SetValidValue(value, true, "Parameterdatei");
                ReportPropertyChanged("Parameterdatei");
                OnParameterdateiChanged();
            }
        }
        private global::System.String _Parameterdatei;
        partial void OnParameterdateiChanging(global::System.String value);
        partial void OnParameterdateiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AktivKZ
        {
            get
            {
                return _AktivKZ;
            }
            set
            {
                OnAktivKZChanging(value);
                ReportPropertyChanging("AktivKZ");
                _AktivKZ = StructuralObject.SetValidValue(value, "AktivKZ");
                ReportPropertyChanged("AktivKZ");
                OnAktivKZChanged();
            }
        }
        private Nullable<global::System.Boolean> _AktivKZ;
        partial void OnAktivKZChanging(Nullable<global::System.Boolean> value);
        partial void OnAktivKZChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StandortKz
        {
            get
            {
                return _StandortKz;
            }
            set
            {
                OnStandortKzChanging(value);
                ReportPropertyChanging("StandortKz");
                _StandortKz = StructuralObject.SetValidValue(value, true, "StandortKz");
                ReportPropertyChanged("StandortKz");
                OnStandortKzChanged();
            }
        }
        private global::System.String _StandortKz;
        partial void OnStandortKzChanging(global::System.String value);
        partial void OnStandortKzChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> O_TimeStamp
        {
            get
            {
                return _O_TimeStamp;
            }
            set
            {
                OnO_TimeStampChanging(value);
                ReportPropertyChanging("O_TimeStamp");
                _O_TimeStamp = StructuralObject.SetValidValue(value, "O_TimeStamp");
                ReportPropertyChanged("O_TimeStamp");
                OnO_TimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _O_TimeStamp;
        partial void OnO_TimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnO_TimeStampChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WZNTModel", Name="GruSysAPiJobSt")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GruSysAPiJobSt : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GruSysAPiJobSt object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="jOB_ID">Initial value of the JOB_ID property.</param>
        public static GruSysAPiJobSt CreateGruSysAPiJobSt(global::System.Int32 id, global::System.Int32 jOB_ID)
        {
            GruSysAPiJobSt gruSysAPiJobSt = new GruSysAPiJobSt();
            gruSysAPiJobSt.ID = id;
            gruSysAPiJobSt.JOB_ID = jOB_ID;
            return gruSysAPiJobSt;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JOB_ID
        {
            get
            {
                return _JOB_ID;
            }
            set
            {
                OnJOB_IDChanging(value);
                ReportPropertyChanging("JOB_ID");
                _JOB_ID = StructuralObject.SetValidValue(value, "JOB_ID");
                ReportPropertyChanged("JOB_ID");
                OnJOB_IDChanged();
            }
        }
        private global::System.Int32 _JOB_ID;
        partial void OnJOB_IDChanging(global::System.Int32 value);
        partial void OnJOB_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Frequenz
        {
            get
            {
                return _Frequenz;
            }
            set
            {
                OnFrequenzChanging(value);
                ReportPropertyChanging("Frequenz");
                _Frequenz = StructuralObject.SetValidValue(value, true, "Frequenz");
                ReportPropertyChanged("Frequenz");
                OnFrequenzChanged();
            }
        }
        private global::System.String _Frequenz;
        partial void OnFrequenzChanging(global::System.String value);
        partial void OnFrequenzChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Startdatum
        {
            get
            {
                return _Startdatum;
            }
            set
            {
                OnStartdatumChanging(value);
                ReportPropertyChanging("Startdatum");
                _Startdatum = StructuralObject.SetValidValue(value, "Startdatum");
                ReportPropertyChanged("Startdatum");
                OnStartdatumChanged();
            }
        }
        private Nullable<global::System.DateTime> _Startdatum;
        partial void OnStartdatumChanging(Nullable<global::System.DateTime> value);
        partial void OnStartdatumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Startzeit
        {
            get
            {
                return _Startzeit;
            }
            set
            {
                OnStartzeitChanging(value);
                ReportPropertyChanging("Startzeit");
                _Startzeit = StructuralObject.SetValidValue(value, "Startzeit");
                ReportPropertyChanged("Startzeit");
                OnStartzeitChanged();
            }
        }
        private Nullable<global::System.DateTime> _Startzeit;
        partial void OnStartzeitChanging(Nullable<global::System.DateTime> value);
        partial void OnStartzeitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AktivKz
        {
            get
            {
                return _AktivKz;
            }
            set
            {
                OnAktivKzChanging(value);
                ReportPropertyChanging("AktivKz");
                _AktivKz = StructuralObject.SetValidValue(value, "AktivKz");
                ReportPropertyChanged("AktivKz");
                OnAktivKzChanged();
            }
        }
        private Nullable<global::System.Boolean> _AktivKz;
        partial void OnAktivKzChanging(Nullable<global::System.Boolean> value);
        partial void OnAktivKzChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> O_TimeStamp
        {
            get
            {
                return _O_TimeStamp;
            }
            set
            {
                OnO_TimeStampChanging(value);
                ReportPropertyChanging("O_TimeStamp");
                _O_TimeStamp = StructuralObject.SetValidValue(value, "O_TimeStamp");
                ReportPropertyChanged("O_TimeStamp");
                OnO_TimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _O_TimeStamp;
        partial void OnO_TimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnO_TimeStampChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WZNTModel", Name="GruSysStandort")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GruSysStandort : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GruSysStandort object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="standortID">Initial value of the StandortID property.</param>
        public static GruSysStandort CreateGruSysStandort(global::System.Int32 id, global::System.String standortID)
        {
            GruSysStandort gruSysStandort = new GruSysStandort();
            gruSysStandort.ID = id;
            gruSysStandort.StandortID = standortID;
            return gruSysStandort;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StandortID
        {
            get
            {
                return _StandortID;
            }
            set
            {
                OnStandortIDChanging(value);
                ReportPropertyChanging("StandortID");
                _StandortID = StructuralObject.SetValidValue(value, false, "StandortID");
                ReportPropertyChanged("StandortID");
                OnStandortIDChanged();
            }
        }
        private global::System.String _StandortID;
        partial void OnStandortIDChanging(global::System.String value);
        partial void OnStandortIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Standort
        {
            get
            {
                return _Standort;
            }
            set
            {
                OnStandortChanging(value);
                ReportPropertyChanging("Standort");
                _Standort = StructuralObject.SetValidValue(value, true, "Standort");
                ReportPropertyChanged("Standort");
                OnStandortChanged();
            }
        }
        private global::System.String _Standort;
        partial void OnStandortChanging(global::System.String value);
        partial void OnStandortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> O_TimeStamp
        {
            get
            {
                return _O_TimeStamp;
            }
            set
            {
                OnO_TimeStampChanging(value);
                ReportPropertyChanging("O_TimeStamp");
                _O_TimeStamp = StructuralObject.SetValidValue(value, "O_TimeStamp");
                ReportPropertyChanged("O_TimeStamp");
                OnO_TimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _O_TimeStamp;
        partial void OnO_TimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnO_TimeStampChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WZNTModel", Name="WZNTArtikel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WZNTArtikel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WZNTArtikel object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static WZNTArtikel CreateWZNTArtikel(global::System.Int32 id)
        {
            WZNTArtikel wZNTArtikel = new WZNTArtikel();
            wZNTArtikel.ID = id;
            return wZNTArtikel;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Artikelnummer
        {
            get
            {
                return _Artikelnummer;
            }
            set
            {
                OnArtikelnummerChanging(value);
                ReportPropertyChanging("Artikelnummer");
                _Artikelnummer = StructuralObject.SetValidValue(value, true, "Artikelnummer");
                ReportPropertyChanged("Artikelnummer");
                OnArtikelnummerChanged();
            }
        }
        private global::System.String _Artikelnummer;
        partial void OnArtikelnummerChanging(global::System.String value);
        partial void OnArtikelnummerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StandortKZ
        {
            get
            {
                return _StandortKZ;
            }
            set
            {
                OnStandortKZChanging(value);
                ReportPropertyChanging("StandortKZ");
                _StandortKZ = StructuralObject.SetValidValue(value, true, "StandortKZ");
                ReportPropertyChanged("StandortKZ");
                OnStandortKZChanged();
            }
        }
        private global::System.String _StandortKZ;
        partial void OnStandortKZChanging(global::System.String value);
        partial void OnStandortKZChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Matchcode
        {
            get
            {
                return _Matchcode;
            }
            set
            {
                OnMatchcodeChanging(value);
                ReportPropertyChanging("Matchcode");
                _Matchcode = StructuralObject.SetValidValue(value, true, "Matchcode");
                ReportPropertyChanged("Matchcode");
                OnMatchcodeChanged();
            }
        }
        private global::System.String _Matchcode;
        partial void OnMatchcodeChanging(global::System.String value);
        partial void OnMatchcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Artikelgruppe
        {
            get
            {
                return _Artikelgruppe;
            }
            set
            {
                OnArtikelgruppeChanging(value);
                ReportPropertyChanging("Artikelgruppe");
                _Artikelgruppe = StructuralObject.SetValidValue(value, true, "Artikelgruppe");
                ReportPropertyChanged("Artikelgruppe");
                OnArtikelgruppeChanged();
            }
        }
        private global::System.String _Artikelgruppe;
        partial void OnArtikelgruppeChanging(global::System.String value);
        partial void OnArtikelgruppeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HArtikelgruppe
        {
            get
            {
                return _HArtikelgruppe;
            }
            set
            {
                OnHArtikelgruppeChanging(value);
                ReportPropertyChanging("HArtikelgruppe");
                _HArtikelgruppe = StructuralObject.SetValidValue(value, true, "HArtikelgruppe");
                ReportPropertyChanged("HArtikelgruppe");
                OnHArtikelgruppeChanged();
            }
        }
        private global::System.String _HArtikelgruppe;
        partial void OnHArtikelgruppeChanging(global::System.String value);
        partial void OnHArtikelgruppeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VArtikelgruppe
        {
            get
            {
                return _VArtikelgruppe;
            }
            set
            {
                OnVArtikelgruppeChanging(value);
                ReportPropertyChanging("VArtikelgruppe");
                _VArtikelgruppe = StructuralObject.SetValidValue(value, true, "VArtikelgruppe");
                ReportPropertyChanged("VArtikelgruppe");
                OnVArtikelgruppeChanged();
            }
        }
        private global::System.String _VArtikelgruppe;
        partial void OnVArtikelgruppeChanging(global::System.String value);
        partial void OnVArtikelgruppeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ArtikelKZ
        {
            get
            {
                return _ArtikelKZ;
            }
            set
            {
                OnArtikelKZChanging(value);
                ReportPropertyChanging("ArtikelKZ");
                _ArtikelKZ = StructuralObject.SetValidValue(value, "ArtikelKZ");
                ReportPropertyChanged("ArtikelKZ");
                OnArtikelKZChanged();
            }
        }
        private Nullable<global::System.Boolean> _ArtikelKZ;
        partial void OnArtikelKZChanging(Nullable<global::System.Boolean> value);
        partial void OnArtikelKZChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserRek1
        {
            get
            {
                return _UserRek1;
            }
            set
            {
                OnUserRek1Changing(value);
                ReportPropertyChanging("UserRek1");
                _UserRek1 = StructuralObject.SetValidValue(value, true, "UserRek1");
                ReportPropertyChanged("UserRek1");
                OnUserRek1Changed();
            }
        }
        private global::System.String _UserRek1;
        partial void OnUserRek1Changing(global::System.String value);
        partial void OnUserRek1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserRek2
        {
            get
            {
                return _UserRek2;
            }
            set
            {
                OnUserRek2Changing(value);
                ReportPropertyChanging("UserRek2");
                _UserRek2 = StructuralObject.SetValidValue(value, true, "UserRek2");
                ReportPropertyChanged("UserRek2");
                OnUserRek2Changed();
            }
        }
        private global::System.String _UserRek2;
        partial void OnUserRek2Changing(global::System.String value);
        partial void OnUserRek2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserRek3
        {
            get
            {
                return _UserRek3;
            }
            set
            {
                OnUserRek3Changing(value);
                ReportPropertyChanging("UserRek3");
                _UserRek3 = StructuralObject.SetValidValue(value, true, "UserRek3");
                ReportPropertyChanged("UserRek3");
                OnUserRek3Changed();
            }
        }
        private global::System.String _UserRek3;
        partial void OnUserRek3Changing(global::System.String value);
        partial void OnUserRek3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Barcode
        {
            get
            {
                return _Barcode;
            }
            set
            {
                OnBarcodeChanging(value);
                ReportPropertyChanging("Barcode");
                _Barcode = StructuralObject.SetValidValue(value, true, "Barcode");
                ReportPropertyChanged("Barcode");
                OnBarcodeChanged();
            }
        }
        private global::System.String _Barcode;
        partial void OnBarcodeChanging(global::System.String value);
        partial void OnBarcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Barcodetyp
        {
            get
            {
                return _Barcodetyp;
            }
            set
            {
                OnBarcodetypChanging(value);
                ReportPropertyChanging("Barcodetyp");
                _Barcodetyp = StructuralObject.SetValidValue(value, true, "Barcodetyp");
                ReportPropertyChanged("Barcodetyp");
                OnBarcodetypChanged();
            }
        }
        private global::System.String _Barcodetyp;
        partial void OnBarcodetypChanging(global::System.String value);
        partial void OnBarcodetypChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FormatBreite
        {
            get
            {
                return _FormatBreite;
            }
            set
            {
                OnFormatBreiteChanging(value);
                ReportPropertyChanging("FormatBreite");
                _FormatBreite = StructuralObject.SetValidValue(value, "FormatBreite");
                ReportPropertyChanged("FormatBreite");
                OnFormatBreiteChanged();
            }
        }
        private Nullable<global::System.Decimal> _FormatBreite;
        partial void OnFormatBreiteChanging(Nullable<global::System.Decimal> value);
        partial void OnFormatBreiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FormatVorschub
        {
            get
            {
                return _FormatVorschub;
            }
            set
            {
                OnFormatVorschubChanging(value);
                ReportPropertyChanging("FormatVorschub");
                _FormatVorschub = StructuralObject.SetValidValue(value, "FormatVorschub");
                ReportPropertyChanged("FormatVorschub");
                OnFormatVorschubChanged();
            }
        }
        private Nullable<global::System.Decimal> _FormatVorschub;
        partial void OnFormatVorschubChanging(Nullable<global::System.Decimal> value);
        partial void OnFormatVorschubChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> DurchmKZ
        {
            get
            {
                return _DurchmKZ;
            }
            set
            {
                OnDurchmKZChanging(value);
                ReportPropertyChanging("DurchmKZ");
                _DurchmKZ = StructuralObject.SetValidValue(value, "DurchmKZ");
                ReportPropertyChanged("DurchmKZ");
                OnDurchmKZChanged();
            }
        }
        private Nullable<global::System.Boolean> _DurchmKZ;
        partial void OnDurchmKZChanging(Nullable<global::System.Boolean> value);
        partial void OnDurchmKZChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormatMe
        {
            get
            {
                return _FormatMe;
            }
            set
            {
                OnFormatMeChanging(value);
                ReportPropertyChanging("FormatMe");
                _FormatMe = StructuralObject.SetValidValue(value, true, "FormatMe");
                ReportPropertyChanged("FormatMe");
                OnFormatMeChanged();
            }
        }
        private global::System.String _FormatMe;
        partial void OnFormatMeChanging(global::System.String value);
        partial void OnFormatMeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Basis
        {
            get
            {
                return StructuralObject.GetValidValue(_Basis);
            }
            set
            {
                OnBasisChanging(value);
                ReportPropertyChanging("Basis");
                _Basis = StructuralObject.SetValidValue(value, true, "Basis");
                ReportPropertyChanged("Basis");
                OnBasisChanged();
            }
        }
        private global::System.Byte[] _Basis;
        partial void OnBasisChanging(global::System.Byte[] value);
        partial void OnBasisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> DocHoeheBKZ
        {
            get
            {
                return _DocHoeheBKZ;
            }
            set
            {
                OnDocHoeheBKZChanging(value);
                ReportPropertyChanging("DocHoeheBKZ");
                _DocHoeheBKZ = StructuralObject.SetValidValue(value, "DocHoeheBKZ");
                ReportPropertyChanged("DocHoeheBKZ");
                OnDocHoeheBKZChanged();
            }
        }
        private Nullable<global::System.Boolean> _DocHoeheBKZ;
        partial void OnDocHoeheBKZChanging(Nullable<global::System.Boolean> value);
        partial void OnDocHoeheBKZChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> DocHoeheVKZ
        {
            get
            {
                return _DocHoeheVKZ;
            }
            set
            {
                OnDocHoeheVKZChanging(value);
                ReportPropertyChanging("DocHoeheVKZ");
                _DocHoeheVKZ = StructuralObject.SetValidValue(value, "DocHoeheVKZ");
                ReportPropertyChanged("DocHoeheVKZ");
                OnDocHoeheVKZChanged();
            }
        }
        private Nullable<global::System.Boolean> _DocHoeheVKZ;
        partial void OnDocHoeheVKZChanging(Nullable<global::System.Boolean> value);
        partial void OnDocHoeheVKZChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ESKOJobID
        {
            get
            {
                return _ESKOJobID;
            }
            set
            {
                OnESKOJobIDChanging(value);
                ReportPropertyChanging("ESKOJobID");
                _ESKOJobID = StructuralObject.SetValidValue(value, "ESKOJobID");
                ReportPropertyChanged("ESKOJobID");
                OnESKOJobIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ESKOJobID;
        partial void OnESKOJobIDChanging(Nullable<global::System.Int32> value);
        partial void OnESKOJobIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_MaschGru
        {
            get
            {
                return _ID_MaschGru;
            }
            set
            {
                OnID_MaschGruChanging(value);
                ReportPropertyChanging("ID_MaschGru");
                _ID_MaschGru = StructuralObject.SetValidValue(value, "ID_MaschGru");
                ReportPropertyChanged("ID_MaschGru");
                OnID_MaschGruChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_MaschGru;
        partial void OnID_MaschGruChanging(Nullable<global::System.Int32> value);
        partial void OnID_MaschGruChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> O_TimeStamp
        {
            get
            {
                return _O_TimeStamp;
            }
            set
            {
                OnO_TimeStampChanging(value);
                ReportPropertyChanging("O_TimeStamp");
                _O_TimeStamp = StructuralObject.SetValidValue(value, "O_TimeStamp");
                ReportPropertyChanged("O_TimeStamp");
                OnO_TimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _O_TimeStamp;
        partial void OnO_TimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnO_TimeStampChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WZNTModel", "fk_WZNTArtikelVarianten_WZNTArtikel", "WZNTArtikelVarianten")]
        public EntityCollection<WZNTArtikelVarianten> WZNTArtikelVarianten
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WZNTArtikelVarianten>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtikel", "WZNTArtikelVarianten");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WZNTArtikelVarianten>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtikel", "WZNTArtikelVarianten", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WZNTModel", Name="WZNTArtikelVarianten")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WZNTArtikelVarianten : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WZNTArtikelVarianten object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iD_Artikel">Initial value of the ID_Artikel property.</param>
        /// <param name="ausprID">Initial value of the AusprID property.</param>
        public static WZNTArtikelVarianten CreateWZNTArtikelVarianten(global::System.Int32 id, global::System.Int32 iD_Artikel, global::System.Int32 ausprID)
        {
            WZNTArtikelVarianten wZNTArtikelVarianten = new WZNTArtikelVarianten();
            wZNTArtikelVarianten.ID = id;
            wZNTArtikelVarianten.ID_Artikel = iD_Artikel;
            wZNTArtikelVarianten.AusprID = ausprID;
            return wZNTArtikelVarianten;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Artikel
        {
            get
            {
                return _ID_Artikel;
            }
            set
            {
                OnID_ArtikelChanging(value);
                ReportPropertyChanging("ID_Artikel");
                _ID_Artikel = StructuralObject.SetValidValue(value, "ID_Artikel");
                ReportPropertyChanged("ID_Artikel");
                OnID_ArtikelChanged();
            }
        }
        private global::System.Int32 _ID_Artikel;
        partial void OnID_ArtikelChanging(global::System.Int32 value);
        partial void OnID_ArtikelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AusprID
        {
            get
            {
                return _AusprID;
            }
            set
            {
                OnAusprIDChanging(value);
                ReportPropertyChanging("AusprID");
                _AusprID = StructuralObject.SetValidValue(value, "AusprID");
                ReportPropertyChanged("AusprID");
                OnAusprIDChanged();
            }
        }
        private global::System.Int32 _AusprID;
        partial void OnAusprIDChanging(global::System.Int32 value);
        partial void OnAusprIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Material
        {
            get
            {
                return _Material;
            }
            set
            {
                OnMaterialChanging(value);
                ReportPropertyChanging("Material");
                _Material = StructuralObject.SetValidValue(value, true, "Material");
                ReportPropertyChanged("Material");
                OnMaterialChanged();
            }
        }
        private global::System.String _Material;
        partial void OnMaterialChanging(global::System.String value);
        partial void OnMaterialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MemoDR
        {
            get
            {
                return _MemoDR;
            }
            set
            {
                OnMemoDRChanging(value);
                ReportPropertyChanging("MemoDR");
                _MemoDR = StructuralObject.SetValidValue(value, true, "MemoDR");
                ReportPropertyChanged("MemoDR");
                OnMemoDRChanged();
            }
        }
        private global::System.String _MemoDR;
        partial void OnMemoDRChanging(global::System.String value);
        partial void OnMemoDRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> DatenE_KZ
        {
            get
            {
                return _DatenE_KZ;
            }
            set
            {
                OnDatenE_KZChanging(value);
                ReportPropertyChanging("DatenE_KZ");
                _DatenE_KZ = StructuralObject.SetValidValue(value, "DatenE_KZ");
                ReportPropertyChanged("DatenE_KZ");
                OnDatenE_KZChanged();
            }
        }
        private Nullable<global::System.Boolean> _DatenE_KZ;
        partial void OnDatenE_KZChanging(Nullable<global::System.Boolean> value);
        partial void OnDatenE_KZChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Freigabe_KZ
        {
            get
            {
                return _Freigabe_KZ;
            }
            set
            {
                OnFreigabe_KZChanging(value);
                ReportPropertyChanging("Freigabe_KZ");
                _Freigabe_KZ = StructuralObject.SetValidValue(value, "Freigabe_KZ");
                ReportPropertyChanged("Freigabe_KZ");
                OnFreigabe_KZChanged();
            }
        }
        private Nullable<global::System.Boolean> _Freigabe_KZ;
        partial void OnFreigabe_KZChanging(Nullable<global::System.Boolean> value);
        partial void OnFreigabe_KZChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Wickelschema
        {
            get
            {
                return _Wickelschema;
            }
            set
            {
                OnWickelschemaChanging(value);
                ReportPropertyChanging("Wickelschema");
                _Wickelschema = StructuralObject.SetValidValue(value, "Wickelschema");
                ReportPropertyChanged("Wickelschema");
                OnWickelschemaChanged();
            }
        }
        private Nullable<global::System.Int32> _Wickelschema;
        partial void OnWickelschemaChanging(Nullable<global::System.Int32> value);
        partial void OnWickelschemaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> O_TimeStamp
        {
            get
            {
                return _O_TimeStamp;
            }
            set
            {
                OnO_TimeStampChanging(value);
                ReportPropertyChanging("O_TimeStamp");
                _O_TimeStamp = StructuralObject.SetValidValue(value, "O_TimeStamp");
                ReportPropertyChanged("O_TimeStamp");
                OnO_TimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _O_TimeStamp;
        partial void OnO_TimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnO_TimeStampChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WZNTModel", "fk_WZNTArtikelVarianten_WZNTArtikel", "WZNTArtikel")]
        public WZNTArtikel WZNTArtikel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WZNTArtikel>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtikel", "WZNTArtikel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WZNTArtikel>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtikel", "WZNTArtikel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WZNTArtikel> WZNTArtikelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WZNTArtikel>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtikel", "WZNTArtikel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WZNTArtikel>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtikel", "WZNTArtikel", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WZNTModel", "fk_WZNTArtikelVarianten_WZNTArtVarAuspr", "WZNTArtVarAuspr")]
        public WZNTArtVarAuspr WZNTArtVarAuspr
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WZNTArtVarAuspr>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtVarAuspr", "WZNTArtVarAuspr").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WZNTArtVarAuspr>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtVarAuspr", "WZNTArtVarAuspr").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WZNTArtVarAuspr> WZNTArtVarAusprReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WZNTArtVarAuspr>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtVarAuspr", "WZNTArtVarAuspr");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WZNTArtVarAuspr>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtVarAuspr", "WZNTArtVarAuspr", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WZNTModel", Name="WZNTArtVarAuspr")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WZNTArtVarAuspr : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WZNTArtVarAuspr object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static WZNTArtVarAuspr CreateWZNTArtVarAuspr(global::System.Int32 id)
        {
            WZNTArtVarAuspr wZNTArtVarAuspr = new WZNTArtVarAuspr();
            wZNTArtVarAuspr.ID = id;
            return wZNTArtVarAuspr;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Auspr1
        {
            get
            {
                return _Auspr1;
            }
            set
            {
                OnAuspr1Changing(value);
                ReportPropertyChanging("Auspr1");
                _Auspr1 = StructuralObject.SetValidValue(value, true, "Auspr1");
                ReportPropertyChanged("Auspr1");
                OnAuspr1Changed();
            }
        }
        private global::System.String _Auspr1;
        partial void OnAuspr1Changing(global::System.String value);
        partial void OnAuspr1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Auspr2
        {
            get
            {
                return _Auspr2;
            }
            set
            {
                OnAuspr2Changing(value);
                ReportPropertyChanging("Auspr2");
                _Auspr2 = StructuralObject.SetValidValue(value, true, "Auspr2");
                ReportPropertyChanged("Auspr2");
                OnAuspr2Changed();
            }
        }
        private global::System.String _Auspr2;
        partial void OnAuspr2Changing(global::System.String value);
        partial void OnAuspr2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BezAuspr1
        {
            get
            {
                return _BezAuspr1;
            }
            set
            {
                OnBezAuspr1Changing(value);
                ReportPropertyChanging("BezAuspr1");
                _BezAuspr1 = StructuralObject.SetValidValue(value, true, "BezAuspr1");
                ReportPropertyChanged("BezAuspr1");
                OnBezAuspr1Changed();
            }
        }
        private global::System.String _BezAuspr1;
        partial void OnBezAuspr1Changing(global::System.String value);
        partial void OnBezAuspr1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BezAuspr2
        {
            get
            {
                return _BezAuspr2;
            }
            set
            {
                OnBezAuspr2Changing(value);
                ReportPropertyChanging("BezAuspr2");
                _BezAuspr2 = StructuralObject.SetValidValue(value, true, "BezAuspr2");
                ReportPropertyChanged("BezAuspr2");
                OnBezAuspr2Changed();
            }
        }
        private global::System.String _BezAuspr2;
        partial void OnBezAuspr2Changing(global::System.String value);
        partial void OnBezAuspr2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> O_TimeStamp
        {
            get
            {
                return _O_TimeStamp;
            }
            set
            {
                OnO_TimeStampChanging(value);
                ReportPropertyChanging("O_TimeStamp");
                _O_TimeStamp = StructuralObject.SetValidValue(value, "O_TimeStamp");
                ReportPropertyChanged("O_TimeStamp");
                OnO_TimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _O_TimeStamp;
        partial void OnO_TimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnO_TimeStampChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WZNTModel", "fk_WZNTArtikelVarianten_WZNTArtVarAuspr", "WZNTArtikelVarianten")]
        public EntityCollection<WZNTArtikelVarianten> WZNTArtikelVarianten
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WZNTArtikelVarianten>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtVarAuspr", "WZNTArtikelVarianten");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WZNTArtikelVarianten>("WZNTModel.fk_WZNTArtikelVarianten_WZNTArtVarAuspr", "WZNTArtikelVarianten", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
